name: music-indexing

dependencies:
  - python==3.6.5
  - numpy==1.15.4
  - scipy==1.0.1
  - scikit-learn==0.20.1
  - pandas==1.1.3
  - jupyter==1.0.0
  - matplotlib==3.3.2
  - pip
  - pip:
    - hnswlib==0.4.0
    - librosa==0.8.0
